### PR TITLE
Time out in DriveTimeCommand

### PR DESCRIPTION
**Pull request by Zedai**

### CODE REVIEW

**Comment by aravindkoneru** [comment]
Don't make pull requests for one line changes. It really defeats the purpose.

**Comment by Zedai** [comment]
K

**Comment by Zedai** [comment]
What would the best way to handle small changes like that be? Comments or something like that?

**Comment by aravindkoneru** [comment]
Yeah, just making a comment on the commit with the proposed change would be ideal.

**Comment by cuuush** [comment]
Better yet, open an issue so the next person doing a major change can implement it.

**Comment by aravindkoneru** [comment]
Damn, Chris got me clean. Just make an issue out of it with a specific
reference to the commit hash, file, and line number.

On Tue, Jan 19, 2016 at 5:40 PM, chriscush765 notifications@github.com
wrote:

> Better yet, open an issue so the next person doing a major change can
> implement it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Team1923/Stronghold_2016/pull/5#issuecomment-173011329
> .

## 

_Aravind Koneru_

**Pull request closed without merging**
